python-clanglite should depend on libclanglite at runtime
Otherwise the recipe test fails with an error like

ImportError: dlopen(/Users/aaronmeurer/anaconda3/conda-bld/python-clanglite_1519593420214/_t_env/lib/python2.7/site-packages/clanglite/__clanglite.so, 2): Library not loaded: @rpath/libclanglite.dylib
  Referenced from: /Users/aaronmeurer/anaconda3/conda-bld/python-clanglite_1519593420214/_t_env/lib/python2.7/site-packages/clanglite/__clanglite.so
  Reason: image not found
TESTS FAILED: python-clanglite-4.0.1-py27_0.tar.bz2